default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password: Madiha@123##
  database: project_management
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: project_management

test:
  <<: *default
  database: project_management_test

production:
  <<: *default
  database: project_management_production
